#pragma once
#define _XOPEN_SOURCE_EXTENDED
#include <ncurses.h>
#include <locale.h>
#include <time.h>
#include <functional>
#include <cstring>
#include <chrono>
#include <thread>
#include "Menu.h"
#include "RtMidi.h"
#include <vector>
#include "consoleHandler.h"
#include "loopHandler.h"
#include <algorithm>
#include <ctime>
#include "SerialHandler.h"
#include "MidiHandler.h"
